### ISSUE TITLE
Failed to open database: no such module: VirtualElementary

### ISSUE THREAD

**Issue by yucai2005** [AlexCovizzi/vscode-sqlite#107]
When I try to connect a sqlite3 database file with Spatialite extension, it comes up a error message "Failed to open database: no such module: VirtualElementary". How can this problem be solved? Thanks.

**Comment by AlexCovizzi** [comment]
Hi @yucai2005, at the moment the extension does not support dot commands. However this functionality and also executing custom SQL scripts every time you open a database (so that you can automatically load the Spatialite extension whenever you open the database) will be the next feature I will be working on.

**Comment by AlexCovizzi** [comment]
Support for loading extensions whenever a database is opened has been introduced in version 0.13.0, with the new setting `sqlite.setupDatabase`
