### ISSUE TITLE
Publish Extension to Open VSX

### ISSUE THREAD

**Issue by ruanmed** [AlexCovizzi/vscode-sqlite#126]
Publishing the extension to Open VSX would be great for VSCodium users.

https://github.com/open-vsx/publish-extensions

**Comment by jankeromnes** [comment]
I tried to make a Pull Request for this, by editing the GitHub Workflow, but since this also builds Pull Requests, I'm not sure that's the right place (you wouldn't want to upload all Pull Requests to OpenVSX, just the `master` branch).

Basically, publishing to OpenVSX is just a matter of running a single command:

```
npx ovsx publish
```

(No dependency needed.) This will use `vsce` to package and upload the extension.

Alternatively, if you already have a `.vsix` file, you can run:

```
npx ovsx publish extension.vsix
```

Then you'll also need to set up a `OVSX_PAT` env variable, for which you can get the value [here](https://open-vsx.org/user-settings/tokens). That's it.

**Comment by AlexCovizzi** [comment]
I'm thinking of adding a new workflow to automatically publish the extension whenever I make a new release, so I can add a step to also publish to OpenVSX, I'll look into it this weekend

**Comment by AlexCovizzi** [comment]
Done, I added a workflow to publish the extension to Open VSX automatically every time there is a new release.
Thanks for the suggestion!
