### ISSUE TITLE
Missing execution permission on included binaries

### ISSUE THREAD

**Issue by amitaiirron** [AlexCovizzi/vscode-sqlite#135]
Installing on a remote session (client on Windows machine, server on Linux), I initially had issues, where the plugin would report it cannot run the executable. After trying to configure it to exiting clients, without success, I increased log level to DEBUG, and found where the included executables are located. Listing them, showed that none of them (2 Linux clients, one for Windows and one for OSX) had execution permission. Adding execution permission made the plugin operational.

I do not know if it is something you, as the plugin developer, control, or if it has to do with permissions getting lost when the plugin is installed on such a client-server configuration, but it would be good if the files **had execution permissions** right from the start.

Cheers, and thanks for the great plugin.

**Comment by AlexCovizzi** [comment]
Hey @amitaiirron!
I'll take a look, it's possible that the execution permission is removed when the extension is published to the marketplace

**Comment by AlexCovizzi** [comment]
Thanks @amitaiirron for pointing this out, turns out it's a know problem when the extension is published from Windows (which I've done until this last version): https://code.visualstudio.com/api/working-with-extensions/publishing-extension#why-does-vsce-not-preserve-file-attributes
This should be solved on the next update since the extensions will be published from github workflow
